version: "3.3"

services:
  postgres-database:
    container_name: usersnacks-postgres-database
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis-database:
    image: redis:latest
    container_name: usersnacks-redis-database
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis-database:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis-database

  usersnacks-api:
    build: .
    image: usersnacks-api
    container_name: usersnacks-api
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres-database
      - redis-database
    links:
      - postgres-database
      - redis-database

  usersnacks-celery:
    image: usersnacks-api
    container_name: usersnacks-celery
    restart: always
    command: celery -A backend.celery:app worker -l info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - usersnacks-api
      - postgres-database
      - redis-database
    links:
      - postgres-database
      - redis-database
